import type { AuctionListing, AuctionSummaryData } from "./types";

export const MOCK_AUCTIONS: AuctionListing[] = [
  {
    id: "1",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "scheduled",
    status: "scheduled",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
  {
    id: "2",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "scheduled",
    status: "scheduled",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
  {
    id: "3",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "scheduled",
    status: "scheduled",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
  {
    id: "4",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "live",
    currentBid: 6200000,
    views: 6004,
    endsIn: "2d 20:08:03",
    currentBids: 5,
    timeLeft: "1m: 12 S",
  },
  {
    id: "5",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "live",
    currentBid: 6200000,
    views: 6004,
    endsIn: "2d 20:08:03",
    currentBids: 5,
    timeLeft: "1m: 12 S",
  },
  {
    id: "6",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "closed",
    currentBid: 5100000,
    views: 6004,
    endsIn: "2d 20:08:03",
  },
  {
    id: "7",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "upcoming",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
  {
    id: "8",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "starting_soon",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
  {
    id: "9",
    code: "AA",
    digits: "777",
    emirate: "DUBAI",
    plateVariant: "private_new_colorful",
    kind: "open",
    status: "paused",
    currentBid: 5100000,
    views: 6004,
    startsIn: "2d 20:08:03",
  },
];

export const DEFAULT_AUCTION_SUMMARY: AuctionSummaryData = {
  currentBiddingLimit: 0,
  minimumDeposit: 5000,
  targetBiddingLimit: 25000,
  depositStatus: "not_submitted",
  currentPrice: 150000,
  checkAmount: 45000,
};

export function getAuctionById(id: string): AuctionListing | undefined {
  return MOCK_AUCTIONS.find((a) => a.id === id) || MOCK_AUCTIONS[3];
}
